### ISSUE TITLE
[Bug]: TechReborn ores aren't vein mining

### ISSUE THREAD

**Issue by madeofstars0** [TheIllusiveC4/VeinMining#126]
### Minecraft Version

1.20.1

### What happened?

Vein mining does not work on techreborn ores, even tho I have made sure they are all added to the `#c:ores` tag with kubejs. I also tried specifying the "#techreborn:ores" in both blocksList and groupsList.

Ultimately I tried 3 configurations:

(the default, as generated by the mod)
```toml
blocks = "CONFIG_LIST"
blocksList = ["#c:ores", "#forge:ores", "#minecraft:logs"]
blocksListType = "ALLOW"
groupsList = [...{{{ that huge list of tags, like #c:iron_ores }}}...]
```

(specifying only ores as the group and blocks tag)
```toml
blocks = "CONFIG_LIST"
blocksList = ["#c:ores", "#forge:ores", "#minecraft:logs"]
blocksListType = "ALLOW"
groupsList = ["#c:ores"]
```

(specifying techreborn's tag techreborn:ores)
```toml
blocks = "CONFIG_LIST"
blocksList = ["#c:ores", "#forge:ores", "#minecraft:logs", "#techreborn:ores"]
blocksListType = "ALLOW"
groupsList = ["#c:ores", "#techreborn:ores"]
```

These 3 configs I was testing in the nether with minecraft:nether_quartz_ore (which was vein mining properly) and techreborn:sphalerite_ore which would only mine individual blocks.

This is a modpack I put together on [modrinth](https://modrinth.com/modpack/lobservatoire-sundered-aletharia) (so you have the list of mods, the server adds luckperms, fabric proxy lite and cross-stitch, since I run this behind a velocity proxy)

I was also able to reproduce this in single player as well (I used 3rd approach above in single player and put this in the next part of this bug report)

### How do you trigger this bug?

1. Install the [modpack](https://modrinth.com/modpack/lobservatoire-sundered-aletharia), I am using PrismLauncher
2. Launch minecraft, create a new world in creative mode. Give yourself a diamond pickaxe, an anvil, veinmining book and silk touch books (both level 1). Add the books to the pickaxe.
3. quit
4. edit the veinmining-server toml file, add `#techreborn:ores` to both blocksList and groupsList
5. launch the game again, either create a bunch of coal ore and tin ore or find them in the overworld. 
6. Switch to survival, mine the coal (observe that it vein mines properly) then mine the tin_ore (observe that it doesn't mine more than one block)

(as a note, disabling the mobcatalog mod clears up the logs, it has a problem in this modpack with its config.
...

### Loader

Fabric

### Loader Version

0.15.10

### API Version

0.92.0+1.20.1

### Mod Version

1.4.1+1.20.1
