### ISSUE TITLE
[Bug]: other type of blocks are not listed for configuration

### ISSUE THREAD

**Issue by V1ncentLiu** [TheIllusiveC4/VeinMining#54]
### Minecraft Version

1.18.1

### What happened?

    Trying to add the corresponding blocks of minerals(i.e. iron blocks, diamond blocks etc.) into the whitelist, and none of the 'combination' seems to work.
    What are the names for the blocks in the vanilla Minecraft? I would like to know the following block's name to add to the configuration:
1. All the blocks of the minerals(iron, gold, copper, diamond, redstone and netherite). 
2. Sand, gravel and clay.

Thank you

The following is parts in veinminig-server.toml that configures blocks, as of now, only the *"#forge:ores"* part works.
```toml
#List of whitelisted/blacklisted blocks or block tags
blocks = ["#forge:ores", "#forge:blocks/iron", "#forge:blocks/gold", "#forge:blocks/diamond", "#forge:blocks/redstone", "#forge:blocks/netherite"]
#Whether the blocks configuration is a whitelist or a blacklist
#Allowed Values: BLACKLIST, WHITELIST
blocksPermission = "WHITELIST"
```

*PS: my Minecraft version is 1.18.2, but it was not listed in the above dropdown list.*

### How do you trigger this bug?

1. Manually piles mineral blocks.
2. Open veinminig-server.toml using */config showfile veinmining SERVER.*
3. Save and close game.
4. Adds block names.
5. Save and close.
6. Restart game.
7. Mine blocks with pickaxe that has the enchant.
8. Blocks still being mined one by one.

### Loader

Forge

### Loader Version

Forge 40.1.16

### Mod Version

Vein Mining 1.18.2 - 0.18
